name: CI-Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'  # Specify the Go version you need

    - name: Checkout private repo
      env:
        PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      run: |
        git clone https://milos-ethernal:${PRIVATE_REPO_TOKEN}@github.com/Ethernal-Tech/apex-bridge.git
        cd apex-bridge

    - name: Build Go project
      run: |
        cd apex-bridge
        go build
        mkdir -p $GITHUB_WORKSPACE/bin
        mv apex-bridge $GITHUB_WORKSPACE/bin/

    - name: Add executable to PATH
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Verify executable
      run: apex-bridge --help